# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: [Histología y Anatomía]
description: [Material de estudio de la cátedra]
